# Generated by Django 4.2 on 2023-04-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '02:00 – 02:30'), (1, '02:30 – 03:00'), (2, '03:00 – 03:30'), (3, '03:30 – 04:00'), (4, '04:00 – 04:30'), (5, '04:30 – 05:00'), (6, '05:00 – 05:30'), (7, '05:30 – 06:00'), (8, '06:30 – 07:00'), (9, '07:00 – 07:30'), (8, '07:30 – 08:00'), (8, '08:00 – 08:30'), (8, '08:30 – 09:00')], default=0),
        ),
    ]
