# Generated by Django 4.2 on 2023-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_category_menuitem_orderlist_ordermenuitem_yourcart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='smritisharmatemp@gmail.com', max_length=254),
        ),
    ]
